List<String> headers = [
  "Accept",
  "Accept-Charset",
  "Accept-Encoding",
  "Accept-Language",
  "Accept-Datetime",
  "Access-Control-Request-Method",
  "Access-Control-Request-Headers",
  "Authorization",
  "Cache-Control (can be used in both requests and responses)",
  "Connection",
  "Content-Length",
  "Content-Type",
  "Cookie",
  "Date",
  "Expect",
  "From",
  "Host (required in HTTP/1.1 requests)",
  "If-Match",
  "If-Modified-Since",
  "If-None-Match",
  "If-Range",
  "If-Unmodified-Since",
  "Max-Forwards",
  "Origin",
  "Pragma",
  "Proxy-Authorization",
  "Range",
  "Referer",
  "TE",
  "User-Agent",
  "Upgrade",
  "X-Requested-With",
  "DNT (Do Not Track)",
  "X-Forwarded-For",
  "X-Forwarded-Host",
  "X-Forwarded-Proto",
  "Front-End-Https",
  "X-Http-Method-Override",
  "X-ATT-DeviceId",
  "X-Wap-Profile",
  "Proxy-Connection",
  "X-UIDH",
  "X-Csrf-Token",
  "X-Request-ID",
  "X-Correlation-ID",
  "Save-Data",
];
